name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      driver_to_build:
        description: 'Path of the driver to build (Where the solution is)'
        default: 'usb/kmdf_fx2'
        required: true
        type: string
        
      platform:
        description: 'Platform the driver will be built'
        required: true
        default: 'x64'
        type: choice
        options:
        - x64
        - arm64
  
      configuration:
        description: 'Configuration the driver will be built'
        required: true
        default: 'Release'
        type: choice
        options:
        - Release
        - Debug

jobs:
  build_drivers:
    name: Build Drivers
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Nuget Packages
        run: nuget restore .\packages.config -PackagesDirectory .\packages\

      - name: Build the driver
        run: .\Build-SampleSet.ps1 -SampleSet ${{ inputs.driver_to_build }} -Configuration ${{ inputs.configuration }} -Platform ${{ inputs.configuration }}

      - name: Build the driver
        run: Get-ChildItem -Recurse
